In [1]:
from requests import get
import pandas as pd
TURMAS_SALAS_HORARIOS = "https://prograd.ufabc.edu.br/pdf/ajuste_2022_3_turmas.xlsx"
turmas_e_salas = get(TURMAS_SALAS_HORARIOS).content

In [2]:
with open("TURMAS_SALAS.xlsx","wb") as turmas:
    turmas.write(turmas_e_salas)

In [3]:
df = pd.read_excel(turmas_e_salas,sheet_name="AJUSTE_2022.3")

In [4]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [5]:
#display(df)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,CURSO,CÓDIGO DE TURMA,Tipo de aula,TURMA,Disciplina,Disciplina,turma,TEORIA,PRÁTICA,teoria COM SALA,...,VAGAS INGRESSANTES,VAGAS PARA VETERANOS,TURMAS ALTA DEMANDA (não é possível soltar dur...,VAGAS TOTAIS,VAGAS RESERVADAS SISU,VAGAS\nREMANESCENTES\n(PODEM OSCILAR DURANTE O...,DOCENTE TEORIA 1,DOCENTE TEORIA 2,DOCENTE PRÁTICA 1,DOCENTE PRÁTICA 2
1,ENGENHARIA AEROESPACIAL,DA1ESZS019-17SB,PRESENCIAL,Aerodinâmica II A1-diurno (São Bernardo do Campo),Aerodinâmica II,ESZS019-17,A1,"segunda das 17:00 às 19:00, semanal ; quarta d...",NaN,"segunda das 17:00 às 19:00, sala A1-S104-SB, s...",...,0,30,-,30,0,18,MARCELO TANAKA HAYASHI,NaN,NaN,NaN
2,ENGENHARIA AEROESPACIAL,DA1ESTS012-17SB,PRESENCIAL,Aeroelasticidade A1-diurno (São Bernardo do Ca...,Aeroelasticidade,ESTS012-17,A1,"terça das 13:00 às 15:00, semanal ; sexta das ...",NaN,"terça das 13:00 às 15:00, sala A2-S307-SB, sem...",...,0,60,-,60,0,27,CESAR MONZU FREIRE,NaN,NaN,NaN
3,BACHARELADO EM MATEMÁTICA,DA1MCTB001-17SA,PRESENCIAL,Álgebra Linear A1-diurno (Santo André),Álgebra Linear,MCTB001-17,A1,"segunda das 10:00 às 12:00, semanal ; quarta d...",NaN,"segunda das 10:00 às 12:00, sala A-107-0, sema...",...,0,44,-,44,0,26,ARMANDO CAPUTI,NaN,NaN,NaN
4,BACHARELADO EM MATEMÁTICA,DB1MCTB001-17SA,PRESENCIAL,Álgebra Linear B1-diurno (Santo André),Álgebra Linear,MCTB001-17,B1,"segunda das 08:00 às 10:00, semanal ; quarta d...",NaN,"segunda das 08:00 às 10:00, sala A-104-0, sema...",...,0,44,-,44,0,18,CRISTIAN FAVIO COLETTI,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,ENGENHARIA AEROESPACIAL,DA1ESTS008-17SB,PRESENCIAL,Vibrações A1-diurno (São Bernardo do Campo),Vibrações,ESTS008-17,A1,"terça das 08:00 às 10:00, semanal ; quinta das...",NaN,"terça das 08:00 às 10:00, sala A2-S305-SB, sem...",...,0,30,-,30,0,20,LEONARDO DE OLIVE FERREIRA,NaN,NaN,NaN
1056,ENGENHARIA AEROESPACIAL,Na1ESTS008-17SB,PRESENCIAL,Vibrações a1-noturno (São Bernardo do Campo),Vibrações,ESTS008-17,a1,"terça das 19:00 às 21:00, semanal ; quinta das...",NaN,"terça das 19:00 às 21:00, sala A2-S203-SB, sem...",...,0,60,-,60,0,0,MARCELO ARAUJO DA SILVA,NaN,NaN,NaN
1057,BACHARELADO EM CIÊNCIA DA COMPUTAÇÃO,NA1MCZA030-17SA,PRESENCIAL,Vida Artificial na Computação A1-noturno (Sant...,Vida Artificial na Computação,MCZA030-17,A1,"sexta das 19:00 às 21:00, semanal",NaN,"sexta das 19:00 às 21:00, sala S-301-2, semanal",...,0,72,SIM,72,0,0,MARIA DAS GRAÇAS BRUNO MARIETTO,NaN,NaN,NaN
1058,BACHARELADO EM CIÊNCIAS BIOLÓGICAS,DA1NHT1064-15SA,PRESENCIAL,Zoologia de Invertebrados II A1-diurno (Santo ...,Zoologia de Invertebrados II,NHT1064-15,A1,"segunda das 10:00 às 12:00, semanal","terça das 08:00 às 12:00, semanal","segunda das 10:00 às 12:00, sala S-304-2, sema...",...,0,30,-,30,0,20,IVES HAIFIG,NaN,IVES HAIFIG,NaN
1059,BACHARELADO EM CIÊNCIAS BIOLÓGICAS,NA1NHT1064-15SA,PRESENCIAL,Zoologia de Invertebrados II A1-noturno (Santo...,Zoologia de Invertebrados II,NHT1064-15,A1,"segunda das 21:00 às 23:00, semanal","terça das 19:00 às 23:00, semanal","segunda das 21:00 às 23:00, sala S-304-2, sema...",...,0,31,-,31,0,0,TIAGO FERNANDES CARRIJO,NaN,TIAGO FERNANDES CARRIJO,NaN

In [6]:
df.columns = df.iloc[0]

In [7]:
df.drop(index=df.index[0], axis=0, inplace=True)

In [8]:
df.columns

Index(['CURSO', 'CÓDIGO DE TURMA', 'Tipo de aula', 'TURMA', 'Disciplina',
       'Disciplina', 'turma', 'TEORIA', 'PRÁTICA', 'teoria COM SALA',
       'prática  COM SALA', 'CAMPUS', 'TURNO', 'T-P-I', 'VAGAS TOTAIS',
       'VAGAS INGRESSANTES', 'VAGAS PARA VETERANOS',
       'TURMAS ALTA DEMANDA (não é possível soltar durante o ajuste)',
       'VAGAS TOTAIS', 'VAGAS RESERVADAS SISU',
       'VAGAS\nREMANESCENTES\n(PODEM OSCILAR DURANTE O AJUSTE)',
       'DOCENTE TEORIA 1', 'DOCENTE TEORIA 2', 'DOCENTE PRÁTICA 1',
       'DOCENTE PRÁTICA 2'],
      dtype='object', name=0)

In [14]:
display(df["TEORIA"])

KeyError: 'TEORIA'

In [9]:
from openpyxl import load_workbook
import pandas as pd

wb = load_workbook('TURMAS_SALAS.xlsx')
ws = wb['AJUSTE_2022.3']

# data = ws.values
# # Get the first line in file as a header line
# columns = next(data)[0:]
# # Create a DataFrame based on the second and subsequent lines of data
# df = pd.DataFrame(data, columns=columns)

In [10]:
display(ws)

In [11]:
data = ws.values
# Get the first line in file as a header line
columns = next(data)[0:]
# Create a DataFrame based on the second and subsequent lines of data
df = pd.DataFrame(data, columns=columns)

In [12]:
display(df)

,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
0,CURSO,CÓDIGO DE TURMA,Tipo de aula,TURMA,Disciplina,Disciplina,turma,TEORIA,PRÁTICA,teoria COM SALA,...,VAGAS INGRESSANTES,VAGAS PARA VETERANOS,TURMAS ALTA DEMANDA (não é possível soltar dur...,VAGAS TOTAIS,VAGAS RESERVADAS SISU,VAGAS\nREMANESCENTES\n(PODEM OSCILAR DURANTE O...,DOCENTE TEORIA 1,DOCENTE TEORIA 2,DOCENTE PRÁTICA 1,DOCENTE PRÁTICA 2
1,=' turmas sistema atual'!A2,=' turmas sistema atual'!B2,PRESENCIAL,=' turmas sistema atual'!C2,=' turmas sistema atual'!E2,=' turmas sistema atual'!G2,=' turmas sistema atual'!H2,=' turmas sistema atual'!AB2,=' turmas sistema atual'!AC2,=' turmas sistema atual'!I2,...,=' turmas sistema atual'!O2,=O3-P3,"=VLOOKUP(B3,preenchimento!$A$2:$G$1067,7,FALSE)",=' turmas sistema atual'!N2,=' turmas sistema atual'!O2,"=VLOOKUP(B3,preenchimento!$A$2:$J$1067,10,FALSE)",=UPPER(' turmas sistema atual'!P2),=UPPER(' turmas sistema atual'!R2),=UPPER(' turmas sistema atual'!T2),=UPPER(' turmas sistema atual'!V2)
2,=' turmas sistema atual'!A3,=' turmas sistema atual'!B3,PRESENCIAL,=' turmas sistema atual'!C3,=' turmas sistema atual'!E3,=' turmas sistema atual'!G3,=' turmas sistema atual'!H3,=' turmas sistema atual'!AB3,=' turmas sistema atual'!AC3,=' turmas sistema atual'!I3,...,=' turmas sistema atual'!O3,=O4-P4,"=VLOOKUP(B4,preenchimento!$A$2:$G$1067,7,FALSE)",=' turmas sistema atual'!N3,=' turmas sistema atual'!O3,"=VLOOKUP(B4,preenchimento!$A$2:$J$1067,10,FALSE)",=UPPER(' turmas sistema atual'!P3),=UPPER(' turmas sistema atual'!R3),=UPPER(' turmas sistema atual'!T3),=UPPER(' turmas sistema atual'!V3)
3,=' turmas sistema atual'!A4,=' turmas sistema atual'!B4,PRESENCIAL,=' turmas sistema atual'!C4,=' turmas sistema atual'!E4,=' turmas sistema atual'!G4,=' turmas sistema atual'!H4,=' turmas sistema atual'!AB4,=' turmas sistema atual'!AC4,=' turmas sistema atual'!I4,...,=' turmas sistema atual'!O4,=O5-P5,"=VLOOKUP(B5,preenchimento!$A$2:$G$1067,7,FALSE)",=' turmas sistema atual'!N4,=' turmas sistema atual'!O4,"=VLOOKUP(B5,preenchimento!$A$2:$J$1067,10,FALSE)",=UPPER(' turmas sistema atual'!P4),=UPPER(' turmas sistema atual'!R4),=UPPER(' turmas sistema atual'!T4),=UPPER(' turmas sistema atual'!V4)
4,=' turmas sistema atual'!A5,=' turmas sistema atual'!B5,PRESENCIAL,=' turmas sistema atual'!C5,=' turmas sistema atual'!E5,=' turmas sistema atual'!G5,=' turmas sistema atual'!H5,=' turmas sistema atual'!AB5,=' turmas sistema atual'!AC5,=' turmas sistema atual'!I5,...,=' turmas sistema atual'!O5,=O6-P6,"=VLOOKUP(B6,preenchimento!$A$2:$G$1067,7,FALSE)",=' turmas sistema atual'!N5,=' turmas sistema atual'!O5,"=VLOOKUP(B6,preenchimento!$A$2:$J$1067,10,FALSE)",=UPPER(' turmas sistema atual'!P5),=UPPER(' turmas sistema atual'!R5),=UPPER(' turmas sistema atual'!T5),=UPPER(' turmas sistema atual'!V5)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,=' turmas sistema atual'!A1056,=' turmas sistema atual'!B1056,PRESENCIAL,=' turmas sistema atual'!C1056,=' turmas sistema atual'!E1056,=' turmas sistema atual'!G1056,=' turmas sistema atual'!H1056,=' turmas sistema atual'!AB1056,=' turmas sistema atual'!AC1056,=' turmas sistema atual'!I1056,...,=' turmas sistema atual'!O1056,=O1057-P1057,"=VLOOKUP(B1057,preenchimento!$A$2:$G$1067,7,FA...",=' turmas sistema atual'!N1056,=' turmas sistema atual'!O1056,"=VLOOKUP(B1057,preenchimento!$A$2:$J$1067,10,F...",=UPPER(' turmas sistema atual'!P1056),=UPPER(' turmas sistema atual'!R1056),=UPPER(' turmas sistema atual'!T1056),=UPPER(' turmas sistema atual'!V1056)
1056,=' turmas sistema atual'!A1057,=' turmas sistema atual'!B1057,PRESENCIAL,=' turmas sistema atual'!C1057,=' turmas sistema atual'!E1057,=' turmas sistema atual'!G1057,=' turmas sistema atual'!H1057,=' turmas sistema atual'!AB1057,=' turmas sistema atual'!AC1057,=' turmas sistema atual'!I1057,...,=' turmas sistema atual'!O1057,=O1058-P1058,"=VLOOKUP(B1058,preenchimento!$A$2:$G$1067,7,FA...",=' turmas sistema atual'!N1057,=' turmas sistema atual'!O1057,"=VLOOKUP(B1058,preenchimento!$A$2:$J$1067,10,F...",=UPPER(' turmas sistema atual'!P1057),=UPPER(' turmas sistema atual'!R1057),=UPPER(' turmas sistema atual'!T1057),=UPPER(' turmas sistema atual'!V1057)
1057,=' turmas sistema atual'!A1058,=' turmas sistema atual'!B1058,PRESENCIAL,=' turmas sistema atual'!C1058,=' turmas sistema atual'!E1058,=' turmas sistema atual'!G1058,=' turmas sistema atual'!H1058,=' turmas sistema atual'!AB1058,=' turmas sistema atual'!AC1058,=' turmas sistema atual'!I1058,...,=' turmas sistema atual'!O1058,=O1059-P1059,"=VLOOKUP(B1059,preenchimento!$A$2:$G$1067,7,FA...",=' turmas sistema atual'!N1058,=' turmas sistema atual'!O1058,"=VLOOKUP(B1059,preenchimento!$A$2:$J$1067,10,F...",=UPPER(' turmas sistema atual'!P1058),=UPPER(' turmas sistema atual'!R1058),=UPPER(' turmas sistema atual'!T1058),=UPPER(' turmas sistema atual'!V1058)
1058,=' turmas sistema atual'!A1059,=' turmas sistema atual'!B1059,PRESENCIAL,=' turmas sistema atual'!C1059,=' turmas sistema atual'!E1059,=' turmas sistema atual'!G1059,=' turmas sistema atual'!H1059,=' turmas sistema atual'!AB1059,=' turmas sistema atual'!AC1059,=' turmas sistema atual'!I1059,...,=' turmas sistema atual'!O1059,=O1060-P1060,"=VLOOKUP(B1060,preenchimento!$A$2:$G$1067,7,FA...",=' turmas sistema atual'!N1059,=' turmas sistema atual'!O1059,"=VLOOKUP(B1060,preenchimento!$A$2:$J$1067,10,F...",=UPPER(' turmas sistema atual'!P1059),=UPPER(' turmas sistema atual'!R1059),=UPPER(' turmas sistema atual'!T1059),=UPPER(' turmas sistema atual'!V1059)
1059,=' turmas sistema atual'!A1060,=' turmas sistema atual'!B1060,PRESENCIAL,=' turmas sistema atual'!C1060,=' turmas sistema atual'!E1060,=' turmas sistema atual'!G1060,=' turmas sistema atual'!H1060,=' turmas sistema atual'!AB1060,=' turmas sistema atual'!AC1060,=' turmas sistema atual'!I1060,...,=' turmas sistema atual'!O1060,=O1061-P1061,"=VLOOKUP(B1061,preenchimento!$A$2:$G$1067,7,FA...",=' turmas sistema atual'!N1060,=' turmas sistema atual'!O1060,"=VLOOKUP(B1061,preenchimento!$A$2:$J$1067,10,F...",=UPPER(' turmas sistema atual'!P1060),=UPPER(' turmas sistema atual'!R1060),=UPPER(' turmas sistema atual'!T1060),=UPPER(' turmas sistema atual'!V1060)